[2024-05-11 12:35:20] Error: Could not find product with itemIdenifier: 15 in the inventory catalog.. Stack trace: 
se.kth.IV1350.integration.InvalidItemIdentifierException: Error: Could not find product with itemIdenifier: 15 in the inventory catalog.
	at se.kth.IV1350.integration.ExternalInventorySystem.getItemFromDB(ExternalInventorySystem.java:34)
	at se.kth.IV1350.controller.Controller.scanItem(Controller.java:81)
	at se.kth.IV1350.view.View.run(View.java:41)
	at se.kth.IV1350.startup.Main.main(Main.java:19)
[2024-05-11 12:35:20] Error: connection to databse failed. Stack trace: 
se.kth.IV1350.integration.DatabaseFailureException: Error: connection to databse failed
	at se.kth.IV1350.integration.ExternalInventorySystem.getItemFromDB(ExternalInventorySystem.java:28)
	at se.kth.IV1350.controller.Controller.scanItem(Controller.java:81)
	at se.kth.IV1350.view.View.run(View.java:50)
	at se.kth.IV1350.startup.Main.main(Main.java:19)
